project_name: redirector
before:
  hooks:
    - go mod download
builds:
  - id: main
    main: ./cmd/redirector
    binary: redirector
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.gitcommit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: main
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - main
    format: zip

release:
  prerelease: auto
